version: '3.4'

services:
  nginx:
    image: k0ka/nginx-geoip2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf
    command: bash -c "
      mkdir /var/geoip2 &&
      git clone https://github.com/ar414-com/nginx-geoip2 &&
      cd nginx-geoip2 &&
      tar -zxvf GeoLite2-City_20200519.tar.gz &&
      mv ./GeoLite2-City_20200519/GeoLite2-City.mmdb /var/geoip2 &&
      tar -zxvf GeoLite2-Country_20200519.tar.gz &&
      mv ./GeoLite2-Country_20200519/GeoLite2-Country.mmdb /var/geoip2
     "
    
  frps:
    image: snowdreamtech/frps:latest
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ./frps.ini/:/etc/frp/frps.ini
