version: '3.4'

services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf/:/etc/nginx/nginx.conf
    
  frps:
    image: snowdreamtech/frps:latest
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ./frps.ini/:/etc/frp/frps.ini
