version: '3.4'

services:
  nginx:
    image: k0ka/nginx-geoip2
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_log/:/var/log/nginx/
      - ./nginx-geoip2/GeoLite2-City_20200519/GeoLite2-City.mmdb:/var/geoip2/GeoLite2-City.mmdb
    
  frps:
    image: snowdreamtech/frps:latest
    restart: always
    ports:
      - 7000:7000
    volumes:
      - ./frps.ini/:/etc/frp/frps.ini
